/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Re-export types from the shared schema package
export * from '@iiitdwd/schema';

// Keep the generated query types
export interface SanityQueries {
  '*[_type == "faculty" && facultyId == $id] {\n  "id": facultyId,\n  "photo": content.card.photo,\n  content\n}': GetFacultyDetailsResult;
  '*[_type == "faculty"] {\n  "id": facultyId\n}': GetAllFacultiesResult;
  '*[_type == "faculty"]': QueryFacultyResult;
  '*[_type == "visitor"] {\n  title,\n  profiles[] {\n    title,\n    content,\n    imageURL\n  }\n}': GetAllVisitorsResult;
  '*[_type == "staff"] {\n  title,\n  profiles[] {\n    title,\n    content,\n    imageURL\n  }\n}': GetAllStaffResult;
  '*[_type == "senate"] {\n  title,\n  profiles[] {\n    title,\n    content,\n    imageURL\n  }\n}': GetAllSenateResult;
  '*[_type == "formerDirector"] {\n  title,\n  profiles[] {\n    title,\n    content,\n    imageURL\n  }\n}': GetFormerDirectorResult;
  '*[_type == "chairPerson"] {\n  title,\n  profiles[] {\n    title,\n    content,\n    imageURL\n  }\n}': GetChairpersonResult;
  '*[_type == "boardOfGovernor"] {\n  title,\n  profiles[] {\n    title,\n    content,\n    imageURL\n  }\n}': GetBoardResult;
  '*[_type == "formerBoardOfGovernor"] {\n  title,\n  profiles[] {\n    title,\n    content,\n    imageURL\n  }\n}': GetFormerBoardResult;
  '*[_type == "announcement"]{\n  link,\n  month,\n  new,\n  text,\n  year,\n  date,\n}': GetAnnouncementsResult;
  '*[_type == "linksStructure"]': GetLinksResult;
  '*[_type == "descriptionStructure"]': GetDescriptionResult;
  '*[_type == "about"]{\n  coreValues[] {\n    id,\n    text,\n  },\n}': GetAboutResult;
  '*[_type == "researchProfiles"] {\n  title,\n  profiles[] {\n    title,\n    content,\n    imageURL\n  }\n}': GetResearchResult;
  '*[_type == "research_advertisement"]{\n  time,\n  lastDate,\n  generalInstructions,\n  applicationForm\n}': GetResearchAdvertisementResult;
  '*[_type == "campusData"] {\n  title,\n  href,\n  imageUrl\n}\n': GetCampusDataResult;
  '*[_type == "facility"] {\n  title,\n  blockName,\n  items,\n  imageUrl\n}': GetFacilitiesResult;
  '*[_type == "krcData"] {\n  title,\n  description,\n  accessInfo,\n  buttonText,\n  link\n}\n': GetKrcDataResult;
  '*[_type == "krcDataTel"] {\n  title,\n  description,\n  accessInfo,\n  buttonText,\n  link\n}\n': GetKrcDataTelResult;
  '*[_type == "krcDataTelFull"] {\n  heading,\n  card[] {\n    title,\n    description,\n    accessInfo,\n    buttonText,\n    link\n  }\n}': GetKrcDataTelFullResult;
  '*[_type == "contactData"][0] {\n  generalQueries[]->{\n      name,\n      designation,\n      contactNumber,\n      category->{\n          category\n      }\n  },\n  hostelRelatedQueries[]->{\n      name,\n      designation,\n      contactNumber,\n      category->{\n          category\n      }\n  },\n  academicQueries[]->{\n      name,\n      designation,\n      contactNumber,\n      category->{\n          category\n      }\n  },\n  careerGuidanceCell[]->{\n      name,\n      designation,\n      contactNumber,\n      category->{\n          category\n      }\n  },\n  feeRelatedQueries[]->{\n      name,\n      designation,\n      contactNumber,\n      category->{\n          category\n      }\n  },\n  scholarshipLoansQueries[]->{\n      name,\n      designation,\n      contactNumber,\n      category->{\n          category\n      }\n  }\n}': GetContactInfoResult;
  '*[_type == "mainCarouselImage"]': QueryCarouselResult;
  '*[_type == "event"]': QueryEventsResult;
  '*[_type == "event"] {"eventId": id}': QueryEventIdsResult;
  '*[_type == "event" && id == $id][0]': QueryEventByIdResult;
  '*[_type == "gallery"]': QueryGalleryResult;
  '*[_type == "program"]': QueryProgramsResult;
  '*[_type == "annualReport"]': QueryReportResult;
  '*[_type == "job"]': QueryJobsResult;
  '*[_type == "tender"]': QueryTendersResult;
  '*[_type == "nirf"]': QueryNirfReportsResult;
}

// Query result types
export interface GetFacultyDetailsResult {
  id: string;
  photo: string;
  content: {
    body: {
      profile_text: string;
      interest_areas: string[];
    };
    card: {
      position: string[];
      cabin_number: string;
      department: string;
      PhD: string;
      mail_id: string;
      photo: string;
      designation: string;
    };
    head: {
      profile_pdf: string;
      name: string;
    };
  };
}

export interface GetAllFacultiesResult {
  id: string;
}

export interface QueryFacultyResult {
  facultyId: string;
  content: {
    body: {
      profile_text: string;
      interest_areas: string[];
    };
    card: {
      position: string[];
      cabin_number: string;
      department: string;
      PhD: string;
      mail_id: string;
      photo: string;
      designation: string;
    };
    head: {
      profile_pdf: string;
      name: string;
    };
  };
}

export interface GetAllVisitorsResult {
  title: string;
  profiles: {
    title: string;
    content: string[];
    imageURL: string;
  }[];
}

export interface GetAllStaffResult {
  title: string;
  profiles: {
    title: string;
    content: string[];
    imageURL: string;
  }[];
}

export interface GetAllSenateResult {
  title: string;
  profiles: {
    title: string;
    content: string[];
    imageURL: string;
  }[];
}

export interface GetFormerDirectorResult {
  title: string;
  profiles: {
    title: string;
    content: string[];
    imageURL: string;
  }[];
}

export interface GetChairpersonResult {
  title: string;
  profiles: {
    title: string;
    content: string[];
    imageURL: string;
  }[];
}

export interface GetBoardResult {
  title: string;
  profiles: {
    title: string;
    content: string[];
    imageURL: string;
  }[];
}

export interface GetFormerBoardResult {
  title: string;
  profiles: {
    title: string;
    content: string[];
    imageURL: string;
  }[];
}

export interface GetAnnouncementsResult {
  link: string;
  month: string;
  new: boolean;
  text: string;
  year: string;
  date: string;
}

export interface GetLinksResult {
  title: string;
  links: {
    title: string;
    href: string;
  }[];
}

export interface GetDescriptionResult {
  title: string;
  description: string;
}

export interface GetAboutResult {
  coreValues: {
    id: string;
    text: string;
  }[];
}

export interface GetResearchResult {
  title: string;
  profiles: {
    title: string;
    content: string[];
    imageURL: string;
  }[];
}

export interface GetResearchAdvertisementResult {
  time: string;
  lastDate: string;
  generalInstructions: string;
  applicationForm: string;
}

export interface GetCampusDataResult {
  title: string;
  href: string;
  imageUrl: string;
}

export interface GetFacilitiesResult {
  title: string;
  blockName: string;
  items: string[];
  imageUrl: string;
}

export interface GetKrcDataResult {
  title: string;
  description: string;
  accessInfo: string;
  buttonText: string;
  link: string;
}

export interface GetKrcDataTelResult {
  title: string;
  description: string;
  accessInfo: string;
  buttonText: string;
  link: string;
}

export interface GetKrcDataTelFullResult {
  heading: string;
  card: {
    title: string;
    description: string;
    accessInfo: string;
    buttonText: string;
    link: string;
  }[];
}

export interface GetContactInfoResult {
  generalQueries: {
    name: string;
    designation: string;
    contactNumber: string;
    category: {
      category: string;
    };
  }[];
  hostelRelatedQueries: {
    name: string;
    designation: string;
    contactNumber: string;
    category: {
      category: string;
    };
  }[];
  academicQueries: {
    name: string;
    designation: string;
    contactNumber: string;
    category: {
      category: string;
    };
  }[];
  careerGuidanceCell: {
    name: string;
    designation: string;
    contactNumber: string;
    category: {
      category: string;
    };
  }[];
  feeRelatedQueries: {
    name: string;
    designation: string;
    contactNumber: string;
    category: {
      category: string;
    };
  }[];
  scholarshipLoansQueries: {
    name: string;
    designation: string;
    contactNumber: string;
    category: {
      category: string;
    };
  }[];
}

export interface QueryCarouselResult {
  image: {
    asset: {
      _ref: string;
    };
  };
  title: string;
  description: string;
  link: string;
}

export interface QueryEventsResult {
  title: string;
  description: string;
  date: string;
  link: string;
}

export interface QueryEventIdsResult {
  eventId: string;
}

export interface QueryEventByIdResult {
  title: string;
  description: string;
  date: string;
  link: string;
}

export interface QueryGalleryResult {
  title: string;
  image: {
    asset: {
      _ref: string;
    };
  };
}

export interface QueryProgramsResult {
  title: string;
  description: string;
  link: string;
}

export interface QueryReportResult {
  title: string;
  year: string;
  link: string;
}

export interface QueryJobsResult {
  title: string;
  description: string;
  lastDate: string;
  link: string;
}

export interface QueryTendersResult {
  title: string;
  description: string;
  lastDate: string;
  link: string;
}

export interface QueryNirfReportsResult {
  title: string;
  year: string;
  link: string;
}
